modules/forum/views.py
from flask import Blueprint, render_template, request, flash, redirect, url_for, g
from werkzeug.security import generate_password_hash
from .models import Article, Category, Classification, Comment
from ..auth.models import User
from ..auth.views.auth import login_request_update
from ..forum.forms import Personal_info_edit_form, Change_password_form, Article_form_user, Comment_form_user
from ..admin.utils import upload_file
from Project_public import db
# print(__name__)
path_forum = Blueprint('forum', __name__, url_prefix='/forum', template_folder='templates', static_folder='static')
# name: views
def index():
    #if you want to have a test, use this: articles_showing = [1, 2, 3]

    page = request.args.get('page', 1, type=int)
    pagination = Article.query.order_by(Article.article_id).paginate(page=page, per_page=10, error_out=False)
    articles_showing = pagination.items
    return render_template('index.html', articles = articles_showing, pagination=pagination)
# @path_forum.route('/')
# def hello_world():  # put application's code here
#     return render_template('index.html')
    # return 'Hello World!'

@path_forum.route('/personal')
@login_request_update
def personal_index():
    return render_template('forum/personal_page.html')

@path_forum.route('/personal/edit/info/<int:user_id>', methods=['GET','POST'])
@login_request_update
def personal_info_update(user_id):
    user_using = User.query.get(user_id)
    form_using = Personal_info_edit_form(
        username=user_using.user_name,
        portrait=user_using.head_portrait,
    )
    if form_using.validate_on_submit():
        user_using.user_name = form_using.username.data
        file_update = form_using.portrait.data
        if user_using.head_portrait == file_update:
            user_using.head_portrait = user_using.head_portrait
        else:
            print("pass change")
            portrait_path, portrait_name = upload_file('portrait', file_update)
            file_update.save(portrait_path)
            user_using.head_portrait = f'portrait/{portrait_name}'
        db.session.add(user_using)
        db.session.commit()
        flash(f'basic information of your account {form_using.username.data} has been changed')
        return redirect(url_for('forum.personal_index'))
    return render_template('forum/edit_personal_information.html', form=form_using, user=user_using, key="edit")

@path_forum.route('/personal/password/change', methods=['GET','POST'])
@login_request_update
def personal_change_password():
    user_using = User.query.get(g.user.user_id)
    form_using = Change_password_form()
    if form_using.validate_on_submit():
        if form_using.password.data == form_using.password_confirm.data:
            print('same')
            user_using.password = generate_password_hash(form_using.password.data)
            db.session.add(user_using)
            db.session.commit()
            g.user = user_using
            flash('the password has been changed successfully', 'success')
            return redirect(url_for('forum.personal_change_password'))
        else:
            print('different')
            flash('the two passwords are different', 'fail')
            return redirect(url_for('forum.personal_change_password'))
    return render_template('forum/personal_change_password.html', form=form_using)

@path_forum.route('/personal/articles')
@login_request_update
def personal_article_manage_page():
    page = request.args.get('page', 1, type=int)
    pagination = Article.query.filter_by(user_id=g.user.user_id).order_by(Article.article_id).paginate(page=page, per_page=2, error_out=False)
    articles_show = pagination.items
    return render_template('forum/personal_articles.html', articles=articles_show, pagination=pagination)

@path_forum.route('/personal/article/add', methods=['GET','POST'])
@login_request_update
def personal_add_new_article():
    form_using = Article_form_user()
    form_using.category.choices = [(category.category_id, category.category_name) for category in Category.query.all()]
    form_using.classifications.choices = [(cla.cla_id, cla.cla_name) for cla in Classification.query.all()]


    if form_using.validate_on_submit():
        file = form_using.thumbnail.data
        article_creating = Article(
            article_name=form_using.name.data,
            excerpt=form_using.excerpt.data,
            article_status=form_using.status.data,
            category_id=int(form_using.category.data),
            content=form_using.content.data,
            user_id=g.user.user_id


        )
        if file == None:
            article_creating.thumbnail = None
        else:
            thumbnail_path, thumbnail_name = upload_file('thumbnail', file)
            file.save(thumbnail_path)
            article_creating.thumbnail = f'thumbnail/{thumbnail_name}'
        article_creating.classifications = [Classification.query.get(cla_id) for cla_id in form_using.classifications.data]
        db.session.add(article_creating)
        db.session.commit()
        flash(f'Article {form_using.name.data} has been created')
        return redirect(url_for('forum.personal_article_manage_page'))
    return render_template('forum/personal_add_or_edit_article.html',form= form_using, key="create")

@path_forum.route('/personal/article/edit/<int:article_id>', methods=['GET','POST'])
@login_request_update
def personal_edit_article(article_id):
    article_using = Article.query.get(article_id)
    classifications_using = [cla.cla_id for cla in article_using.classifications]
    form_using = Article_form_user(
        name=article_using.article_name,
        excerpt=article_using.excerpt,
        status=article_using.article_status,
        category=article_using.category.category_id,
        content=article_using.content,
        thumbnail=article_using.thumbnail,
        classifications=classifications_using,
        user_id=g.user.user_id,


    )

    form_using.category.choices = [(category.category_id, category.category_name) for category in Category.query.all()]
    form_using.classifications.choices = [(cla.cla_id, cla.cla_name) for cla in Classification.query.all()]
    if form_using.validate_on_submit():
        article_using.article_name = form_using.name.data
        article_using.excerpt = form_using.excerpt.data
        article_using.article_status = form_using.status.data
        article_using.category_id = int(form_using.category.data)
        article_using.content = form_using.content.data
        file_update = form_using.thumbnail.data
        if article_using.thumbnail == file_update:
            article_using.thumbnail = article_using.thumbnail
        else:
            thumbnail_path, thumbnail_name = upload_file('thumbnail', file_update)
            file_update.save(thumbnail_path)
            article_using.thumbnail = f'thumbnail/{thumbnail_name}'
        article_using.user_id = g.user.user_id
        article_using.classifications = [Classification.query.get(cla_id) for cla_id in form_using.classifications.data]
        db.session.add(article_using)
        db.session.commit()
        flash(f'Article {form_using.name.data} has been edited')
        return redirect(url_for('forum.personal_article_manage_page'))


    return render_template('forum/personal_add_or_edit_article.html', form=form_using, article=article_using, key="edit")

@path_forum.route('/personal/article/delete/<int:article_id>', methods=['GET','POST'])
@login_request_update
def personal_delete_article(article_id):
    article_using = Article.query.get(article_id)
    if article_using:
        db.session.delete(article_using)
        db.session.commit()
        flash(f'the article {article_using.article_name} has been deleted')
        return redirect(url_for('forum.personal_article_manage_page'))


@path_forum.route('/category/<int:cat_id>')
def articles_with_category(cat_id):


    category_using = Category.query.get(cat_id)
    page = request.args.get('page', default=1, type=int)
    pagination = Article.query.filter(Article.category_id == cat_id).paginate(page=page, per_page=2, error_out=False)
    articles_showing = pagination.items
    return render_template('forum/articles_with_cat.html', articles=articles_showing, category=category_using, pagination=pagination)

@path_forum.route('/article/<int:cat_id>/<int:article_id>')
def article_detail(cat_id, article_id):
    form_using = Comment_form_user()
    article_using = Article.query.get(article_id)
    category_using = Category.query.get(cat_id)
    user_using = User.query.get(article_using.user_id)
    comments_using = Comment.query.filter(Comment.article_id==article_id)
    previous_one = Article.query.filter(Article.article_id < article_id).order_by(-Article.article_id).first()
    next_one = Article.query.filter(Article.article_id > article_id).order_by(Article.article_id).first()

    return render_template('forum/article_detail.html', category=category_using, article=article_using, user=user_using,
                           previous_one=previous_one, next_one=next_one, form=form_using, comments=comments_using)
@path_forum.route('/comment/<int:user_id>/<int:article_id>', methods=['GET','POST'])
@login_request_update
def user_send_comment(user_id, article_id):
    form_using = Comment_form_user()
    article_using = Article.query.get(article_id)

    if form_using.validate_on_submit():
        comment_creating = Comment(
            content = form_using.content.data
        )
        comment_creating.user_id = user_id
        comment_creating.article_id = article_id
        db.session.add(comment_creating)
        db.session.commit()
        flash(f'Comment has been created')
        return redirect(url_for('forum.article_detail',
                                cat_id=article_using.category_id, article_id=article_id))



@path_forum.route('/search')
def search():
    words = request.args.get('words')
    page = request.args.get('page', 1, type=int)

modules/forum/templates/forum/article_detail.html
{% extends 'base.html' %}

{% block title %}
    {{ article.article_name }}
{% endblock title %}
{% block main %}
{% block breadcrumb %}
    <nav class="breadcrumb is-small" aria-label="breadcrumbs">
        <ul>
            <li><a href="/">Main page</a></li>
            <li><a href="{{ url_for('forum.articles_with_category', cat_id=category.category_id) }}">{{ category.category_name }}</a></li>
            <li class="is-active"><a href="#" aria-current="page">{{ article.article_name }}</a></li>
        </ul>
    </nav>
{% endblock breadcrumb %}
{% with messages = get_flashed_messages() %}
    <b-message type="is-success">
        {% if messages %}
            <ul class=flashes>
                {% for message in messages %}
                    <li>{{ message }}</li>
                {% endfor %}
            </ul>
        {% endif %}
    </b-message>
{% endwith %}
{% block article_detail %}
<div class="pl-2">
    <h1 class="is-size-3">
        {{ article.article_name }}
    </h1>
    <p class="has-text-grey-light is-size-6 mt-1">
        <span class="icon"><i class="mdi mdi-clipboard-text-clock-outline"></i></span>{{ article.public_date }}
        <span class="icon"><i class="mdi mdi-shape-outline"></i></span>{{ article.category.category_name }}
        <span class="icon"><i class="mdi mdi-account"></i></span>{{ user.user_name }}
        <span class="icon"><i class="mdi mdi-tag-heart-outline"></i></span>{{ article.classifications|join(',') }}
    </p>
    <div class="is-clearfix"></div>
    <div class=" dropdown-divider"></div>
    <div class="is-block has-background-light">
        <div class="columns">
            <div class="column is-three-fifths">
                <figure class="image is-4by3">
                    <img src="/admin/static/{{ article.thumbnail }}" alt="Article Thumbnail">
                </figure>
            </div>
            <div class="column is-flex-direction-column">
                <div class="is-flex is-justify-content-center">
                    <figure class="image ">
                        {% if user.head_portrait == None  %}
                            <img src="/admin/static/default/default_portrait.jpg" alt="User Head Portrait" style="width: 64px; height: 64px;">
                        {% else %}
                            <img src="/admin/static/{{ user.head_portrait }}" alt="User Head Portrait" style="width: 64px; height: 64px;">
                        {% endif %}
                    </figure>

                </div>
                <div class="is-clearfix"></div>
                <div class=" dropdown-divider"></div>
                <div class="is-flex is-justify-content-center">
                    <p class="is-size-4 has-text-black has-text-weight-bold">{{ user.user_name }}</p>
                </div>
            </div>
        </div>
    </div>
    <div class="content has-text-grey mt-1">{{ article.content|safe }}</div>
</div>





{% endblock article_detail %}
<hr>
<div class="is-block">
    <div class="is-pulled-left">
        <h1 class="is-size-4">
            <span class="icon">
                <i class="mdi mdi-comment-account-outline"></i>
            </span>
            Comments
        </h1>
    </div>
    <hr>
    {% if g.user != None %}
        <form action="{{ url_for('forum.user_send_comment', user_id=g.user.user_id, article_id=article.article_id) }}" method="post" class="mt-4" enctype="multipart/form-data">
            {{ form.csrf_token }}
            <div class="field">
{#                {{ form.content.label(class='label') }}#}
                <div class="control">
                    {{ form.content(class='textarea', rows="10", placeholder='Content') }}
                </div>
            </div>
            <div class="is-block">
                <div class="box has-background-light is-shadowless level">
                    <div class="level-right">
                        <input type="submit" value="save" class=" button is-success">
                    </div>
                </div>
            </div>
        </form>
    {% endif %}
</div>
<hr>
    {% for comment in comments %}
            <article class="notification is-info is-light is-clearfix">
                <div class="content">
                    <figure class="image is-pulled-left">
                        {% if comment.user.head_portrait == None  %}
                            <img src="/admin/static/default/default_portrait.jpg" alt="User Head Portrait" style="width: 64px; height: 64px;">
                        {% else %}
                            <img src="/admin/static/{{ comment.user.head_portrait }}" alt="User Head Portrait" style="width: 64px; height: 64px;">
                        {% endif %}
                    </figure>
                    <p class="subtitle">{{ comment.user.user_name }}</p>
                    <div class="content">
                        {{ comment.content }}
                    </div>
                </div>
            </article>
    {% endfor %}
{% endblock main %}

modules/forum/templates/forum/articles_with_cat.html
{% extends 'index.html' %}

{% block pagination %}
    <nav class="pagination is-small" role="navigation" aria-label="pagination">
    {% if pagination.has_prev %}
    <a href="{{ url_for('forum.articles_with_category', cat_id=category.category_id) }}?page={{ pagination.prev_num }}" class="pagination-previous" title="This is the first page">Previous</a>
    {% endif %}
    {% if pagination.has_next %}
    <a href="{{ url_for('forum.articles_with_category', cat_id=category.category_id) }}?page={{ pagination.next_num }}" class="pagination-next">Next page</a>
    {% endif %}

    <ul class="pagination-list">
        {% for page in pagination.iter_pages() %}
            {% if page %}
                {% if page != pagination.page %}
                <li>
                    <a href="{{ url_for('forum.articles_with_category', cat_id=category.category_id) }}?page={{ page }}" class="pagination-link" aria-label="Page 1" aria-current="page">{{ page }}</a>
                </li>
                {% else %}
                <li>
                    <a class="pagination-link is-current" aria-label="Page 1" aria-current="page">{{ page }}</a>
                </li>
                {% endif %}
            {% else %}
                <span class=pagination-ellipsis>&hellip;</span>
            {% endif %}
        {% endfor %}

    </ul>
</nav>
    {% endblock pagination %}
{#                </div>#}
{#                {% endblock main %}#}

modules/forum/templates/forum/edit_personal_information.html
{% extends 'forum/personal_page.html' %}
{% block res_list %}
    <form action="" method="post" class="mt-4" enctype="multipart/form-data">
        {{ form.csrf_token }}
        <div class="field">
            {{ form.username.label(class='label') }}
            <div class="control">
                {{ form.username(class='input', placeholder='username') }}
            </div>
        </div>
        <div class="field">
            {{ form.portrait.label(class='label') }}
            <div class="control">
                {{ form.portrait(class='input',  placeholder='head_portrait') }}
                <p class="help has-text-grey-light">
                    {{ form.portrait.description }}
                </p>
            </div>

<div class="mb-2">

            {% if key=="edit" %}
                {% if user.head_portrait %}
<img height="100" width="100" src="/admin/static/{{ user.head_portrait }}" alt="{{ user.user_name }}">
                {% else %}
                    -_-
                {% endif %}
            {% endif %}
</div>
        </div>

        <div class="is-block">
            <div class="box has-background-light is-shadowless level">
                <div class="level-right">
                    <a href="{{ url_for('forum.personal_index') }}" class="button is-primary is-light mr-2">back</a>
                    <input type="submit" value="save" class=" button is-success">
                </div>
            </div>
        </div>
    </form>
{% endblock res_list%}

modules/forum/templates/forum/index_with_search.html
{% extends 'index.html' %}
{% block pagination %}
     <nav class="pagination is-small" role="navigation" aria-label="pagination">
        {% if pagination.has_prev %}
            <a href="{{ url_for('forum.search') }}?page={{ pagination.prev_num }}&words={{ words }}" class="pagination-previous" title="This is the first page">Previous</a>
        {% endif %}
        {% if pagination.has_next %}
            <a href="{{ url_for('forum.search') }}?page={{ pagination.next_num }}&words={{ words }}" class="pagination-next">Next page</a>
        {% endif %}

        <ul class="pagination-list">
            {% for page in pagination.iter_pages() %}
                {% if page %}
                    {% if page != pagination.page %}
                        <li>
                            <a href="{{ url_for('forum.search') }}?page={{ page }}&words={{ words }}" class="pagination-link" aria-label="Page 1" aria-current="page">{{ page }}</a>
                        </li>
                    {% else %}
                        <li>
                            <a class="pagination-link is-current" aria-label="Page 1" aria-current="page">{{ page }}</a>
                        </li>
                    {% endif %}
                {% else %}
                    <span class=pagination-ellipsis>&hellip;</span>
                {% endif %}
                {% endfor %}
            </ul>
        </nav>
{% endblock pagination %}

modules/forum/templates/forum/personal_articles.html
{% extends 'forum/personal_page.html' %}
{% block res_list %}
<div class="is-block">
    <div class=" is-pulled-left">
        <h1 class=" is-size-4">
            <span class="icon">
                <i class="mdi mdi-file-document-multiple-outline"></i>
            </span>
            Article management
        </h1>
    </div>

    {% block button %}
    <div class="is-pulled-right">
        <a href="{{ url_for('forum.personal_add_new_article') }}" class=" button is-primary is-light">
            <span class="icon"><i class="mdi mdi-plus-thick"></i></span>
            <span>Add a new article</span>
        </a>
    </div>
    {% endblock button %}

    <div class="is-clearfix"></div>
    <div class=" dropdown-divider"></div>


</div>
{% block table_content %}
<div class="table-container">
    <table class="table is-fullwidth is-hoverable is-striped">
        <thead>
            <tr>
              <th>ID</th>
              <th>Name</th>
              <th>Excerpt</th>
              <th>Category</th>
              <th>Classification</th>
              <th>public_date</th>
              <th>action</th>
            </tr>
        </thead>
        <tbody>

            {% for article in articles %}
            <tr>
                <td>{{ article.article_id }}</td>
                <td>{{ article.article_name }}</td>
                <td>{{ article.excerpt }}</td>
                <td>{{ article.category.category_name }}</td>
                <td>{{ article.classifications|join(',') }} </td>
                <td>{{ article.public_date }}</td>
                <td>
                    <div class="tags">
                        <a href="{{ url_for('forum.personal_edit_article', article_id = article.article_id) }}" class="tag is-success is-light">
                            <span class="icon">
                                <i class="mdi mdi-square-edit-outline"></i>
                            </span>
                            Edit
                        </a>
                        <a href="{{ url_for('forum.personal_delete_article', article_id=article.article_id) }}" class="tag is-danger is-light">
                            <span class="icon">
                                <i class="mdi mdi-trash-can-outline"></i>
                            </span>
                            Delete
                        </a>
                    </div>
                </td>
            </tr>
            {% endfor %}

        </tbody>
    </table>
</div>
{% block pagination %}
<nav class="pagination is-small" role="navigation" aria-label="pagination">
    {% if pagination.has_prev %}
    <a href="{{ url_for('forum.personal_article_manage_page') }}?page={{ pagination.prev_num }}" class="pagination-previous" title="This is the first page">Previous</a>
    {% endif %}
    {% if pagination.has_next %}
    <a href="{{ url_for('forum.personal_article_manage_page') }}?page={{ pagination.next_num }}" class="pagination-next">Next page</a>
    {% endif %}

    <ul class="pagination-list">
        {% for page in pagination.iter_pages() %}
            {% if page %}
                {% if page != pagination.page %}
                <li>
                    <a href="{{ url_for('forum.personal_article_manage_page') }}?page={{ page }}" class="pagination-link" aria-label="Page 1" aria-current="page">{{ page }}</a>
                </li>
                {% else %}
                <li>
                    <a class="pagination-link is-current" aria-label="Page 1" aria-current="page">{{ page }}</a>
                </li>
                {% endif %}
            {% else %}
                <span class=pagination-ellipsis>&hellip;</span>
            {% endif %}
        {% endfor %}

    </ul>
</nav>

{% endblock %}
{% endblock table_content %}
{% endblock res_list %}

modules/forum/templates/forum/personal_change_password.html
{% extends 'forum/personal_page.html' %}

{% block flash_message %}
    {% with messages = get_flashed_messages() %}
        {% if messages %}
            {% for message in messages %}
                {% if message == "the password has been changed successfully" %}
                    <b-message type="is-success">
                        <ul class=flashes>
                            <li>{{ message }}</li>
                        </ul>
                    </b-message>
                {% elif message == "the two passwords are different" %}
                    <b-message type="is-danger">
                        <ul class=flashes>
                            <li>{{ message }}</li>
                        </ul>
                    </b-message>
                {% endif %}
            {% endfor %}
        {% endif %}
    {% endwith %}
{% endblock %}

{% block res_list %}

<form action="" method="post" class="mt-4" >
        {{ form.csrf_token }}
        <div class="field">
            {{ form.password.label(class='label') }}
            <div class="control">
                {{ form.password(class='input', placeholder='password') }}
                <p class="help has-text-grey-light">
                    {{ form.password.description }}
                </p>
            </div>
        </div>
        <div class="field">
            {{ form.password_confirm.label(class='label') }}
            <div class="control">
                {{ form.password_confirm(class='input', placeholder='password_confirm') }}
                <p class="help has-text-grey-light">
                    {{ form.password_confirm.description }}
                </p>
            </div>
        </div>
        <div class="is-block">
            <div class="box has-background-light is-shadowless level">
                <div class="level-right">
                    <a href="{{ url_for('forum.personal_index') }}" class="button is-primary is-light mr-2">back</a>
                    <input type="submit" value="save" class=" button is-success">
                </div>
            </div>
        </div>
</form>
{% endblock %}

modules/forum/templates/forum/personal_page.html
{% extends 'admin/index.html' %}
{% block title %}
{{ g.user['user_name'] }}-Personal center
{% endblock title %}
{% block manage %}
    <div class="columns">
    <div class="column is-2">
        <div class="card is-shadowless" style="border-right:solid 1px #eee">
            <div class="card-content">
                <aside class="menu">
                    <p class="menu-label">
                        terminal
                    </p>
                    <ul class="menu-list">
                        <li><a class="{% if request.path == '/forum/' %}is-active{% endif %}"
                            href="{{ url_for('forum.personal_index') }}">Main page</a></li>

                    </ul>
                    <p class="menu-label">
                        ACCOUNT
                    </p>
                    <ul class="menu-list">
                        <li><a href="{{ url_for('forum.personal_info_update', user_id=g.user.user_id) }}">Basic information management</a></li>
                        <li><a href="{{ url_for('forum.personal_change_password') }}">change the password</a></li>
                    </ul>
                    <p class="menu-label">
                        ARTICLE
                    </p>
                    <ul class="menu-list">
                        <li><a href="{{ url_for('forum.personal_article_manage_page') }}">Article management</a></li>
                    </ul>

                </aside>
            </div>
        </div>
    </div>
    <div class="column">
{% block flash_message %}
    {% with messages = get_flashed_messages() %}
        <b-message type="is-success">
          {% if messages %}
              <ul class=flashes>
                {% for message in messages %}
                    <li>{{ message }}</li>
                {% endfor %}
              </ul>
          {% endif %}
        </b-message>
    {% endwith %}
{% endblock %}
        {% block res_list %}


        <div class="tile is-ancestor">
            <div class="tile is-parent">
                <article class="tile is-child notification is-success is-light">
                    <div class="content">
                        <p class="title">Welcome</p>
                        <p class="subtitle">{{ g.user.user_name }}</p>
                        <div class="content">
                            This is Your personal page
                        </div>
                    </div>
                </article>
            </div>
        </div>
                        <div class="column">
                    <div class="columns is-mobile" style="border-bottom: #ededed solid 1px; padding-bottom: 1rem">
                        <div class="column is-narrow">
                            <figure class="image is-96x96">
                                {% if g.user.head_portrait %}
                                <img class="is-rounded" src="/admin/static/{{ g.user['head_portrait'] }}">
                                {% else %}
                                -_-
                                    <p>you haven't give a head portrait</p>
                                {% endif %}

                            </figure>
                        </div>
                    </div>

                    <div class="columns" style="border-bottom: #ededed solid 1px">
                        <div class="column is-2">
                            <span class=" has-text-grey-light">Username</span>
                        </div>
                        <div class="column is-narrow">
                            <span class=" has-text-black-ter">{{ g.user['user_name'] }}</span>
                        </div>
                    </div>
                    <div class="columns" style="border-bottom: #ededed solid 1px">
                        <div class="column is-2">
                            <span class=" has-text-grey-light">Add_date</span>
                        </div>
                        <div class="column is-narrow">
                            <span class=" has-text-black-ter">{{ g.user['add_date'] }}</span>
                        </div>

                    </div>
                        </div>
        {% endblock res_list %}
    </div>
</div>
{% endblock manage %}